### ISSUE TITLE
Transportation data sourcing - 2005

### ISSUE THREAD

**Issue by pawilfahrt** [Metropolitan-Council/ghg-cprg#77]
Identify data sources for 2005 transportation emissions

**Comment by eroten** [comment]
Options for consideration. Will continue to update

## Activity/vehicle miles

The current year (2021) inventory uses StreetLight Data to estimate emissions for origin/destination trips between/within counties. StreetLight's earliest available year is around 2017 (differs by mode and exact data source), so that will not get us to 2005. 

- Statewide data, scaled to the region based on population. Could do some sort of time series of population growth over time. This would be very coarse.
  - [Climate Watch](https://www.climatewatchdata.org/ghg-emissions?end_year=2021&regions=USA%2CUSA.MN&source=Climate%20Watch&start_year=1990)
  - EPA National Emissions Inventory (NEI), interpolating missing data years
  - National Household Travel Survey [NHTS](https://nhts.ornl.gov/), also NextGen [editions](https://nhts.ornl.gov/od/downloads)
- Get MnDOT/WisDOT VMT (interpolate MN 2015 missing data) back to 2005. Obtain data with highest granularity possible, aggregate as needed. This would 
- Run StreetLight analyses for all available years at county and city levels. Compare directly with DOT VMT values and see if there is a consistent value we can use to scale  the VMT estimates to match StreetLight estimates
  - Potential modeling opportunities based on: centerline miles by route system or functional class, population, employment, population density, 
  - Major drawback is that we would only have maybe 6 years of StreetLight data to compare to.
- Use [LODES LEHD](https://lehd.ces.census.gov/data/), back to 2002, to estimate or validate VMT values using the Origin-Destination framework. 
  - LODES is very focused on employee travel. We would have to adjust for this somehow.
 - 

## Emissions factors

Historical emissions factors should account for how the regional fleet has changed over time. Vehicles are newer, which means they are more efficient. We should see the grams per mile value decrease over time.

- Historical MOVES timeseries? MOVES also projects 
- EPA GHG Hub values (annual, back to 2011)

**Comment by eroten** [comment]
Transit data sources

## Activity/ vehicle miles

- Metro Transit has emissions back to ____

## Emissions factors
- Metro Transit values based on their fleet. See work in ghg.sp

**Comment by eroten** [comment]
# TODO here 

write one-pager on GHG data sources and what you should know about them if you want to
